import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/context/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider> */}
          <main className="mx-auto max-w-5xl text-2xl flex gap-2">
            {/* <NavMenu/> */}
            {children}
          </main>
          {/* </Provider> */}
      </body>
    </html>
  );
}
